# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://mobile-academy.io
title: Mobile Academy
email: hello@mobile-academy.io
author: Mobile Academy
description: Mobile Academy is an organistion that conducts workshops related to iOS application develpoment.
about: Mobile Academy is an organistion that conducts workshops related to iOS application develpoment.
copyright: 'Copyright &copy; 2015-2017 Mobile Academy. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/mobacademy
  - title: github
    url: https://github.com/mobile-academy
  - title: facebook
    url: https://facebook.com/mobacademy
